import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Nav from '@/components/Nav'
import Hero from '@/components/Hero'
import Services from '@/components/Services'
import About from '@/components/About'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gradient-to-bl from-[#151B54] to-[#0e41b9]'>
        <Nav/>
        <Hero/>
        <Services/>
        <About/>
        <Projects/>
        <Contact/>
        <Footer/>
      </div>
    </>
  )
}
